name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  PROJECT_ID: new-project-460404
  SERVICE_ACCOUNT_EMAIL: github-actions@new-project-460404.iam.gserviceaccount.com
  REGION: us-central1
  REPO: hello-repo3

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: 'projects/512488159671/locations/global/workloadIdentityPools/github-pool6/providers/github-provider1'
          service_account: ${{ env.SERVICE_ACCOUNT_EMAIL }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Build and Deploy to Cloud Run
        run: |
          gcloud builds submit --tag $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/hello-app2
          gcloud run deploy hello-app2 \
            --image $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/hello-app2 \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated
            --build-service-account projects/new-project-460404/serviceAccounts/BUILD_SERVICE_ACCOUNT
            
